---
title: "Healthy People 2030 Leading Health Indicators in Colorado"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(leaflet)
library(pins)
library(tidyverse)
library(sf)

board <- board_local()
lhi_df_co <- pin_read('lhi_df_co', board = board)
income_poverty_poly <- pin_read('income_poverty_poly', board = board)
```

row
---------------------------------------------------------------------------------------

```{r}
sidebarPanel(
    selectInput("sdoh", "Health Indicator", choices = c("Binge Drinking",
                                                       "Colorectal Cancer Screening",
                                                       "Current Smoking",
                                                       "Diabetes",
                                                       "Physical Health",
                                                       "High Blood Pressure")
        ),
radioButtons("measure_year", "Year", choices = c("2017" = "2017",
                                                            "2018" = "2018"),
                     selected = "2018"),

#radioButtons("income_poverty", "Choose One", choices = c("Median Household Income",
#                                                         "Percent Poverty"))

)
```

Row {data-height=1050}
-----------------------------------------------------------------------

```{r}
    sdoh_values <- reactive({
        lhi_df_co %>% 
        filter(short_question_text == input$sdoh) %>% 
        filter(year == input$measure_year) %>% 
            select(geometry, short_question_text, measure, NAME, data_value) %>% 
            mutate(data_value = as.numeric(data_value))
        
        })

#    income_poverty_values <- reactive({
#        income_poverty_poly %>% 
#            select(input$income_poverty, NAME.y, geometry)
#       })

    
renderLeaflet({
        
        pal <- colorNumeric(palette = "Greys", domain = sdoh_values()$data_value)
        pal_2 <- colorNumeric(palette = "YlOrRd", domain = income_poverty_poly$poverty_percent)
        
            leaflet(sdoh_values()) %>% 
            addTiles() %>% 
            addPolygons(
                        color = NA, weight = NA, smoothFactor = NA,
                        opacity = 1.0, fillOpacity = 0.3, dashArray = NA,
                        fillColor = ~pal(data_value),
                        highlightOptions = highlightOptions(color = "#666",
                                                            dashArray = "",
                                                            weight = 5,
                                                            bringToFront = TRUE),
                        label = ~paste0(NAME, " ", "County", ": ",
                                        "Crude Prevalence = ", data_value)) %>% 
            addLegend(pal = pal, values = ~data_value, opacity = 0.7, title = "Crude Prevalance",,
                      position = "bottomright") %>% 
            addPolylines(data = income_poverty_poly,
                         opacity = 1.0, fillOpacity = 0.5, smoothFactor = 0.5, weight = 3,
                        color = ~pal_2(poverty_percent))
    })

```

